### ISSUE TITLE
Unwanted cli message

### ISSUE THREAD

**Issue by MichaelBellBOM** [schwamster/serverless-certificate-creator#20]
Great plugin,

My only issue is that when I run custom commands, I still get a message about this plugin.  As I was experiment with a custom command that would get an exact output, which I cannot do with the package version line being printed.

Ideally the line should only be displayed when running the deploy, create-cert and info and not when running custom commands (unless those custom commands use this plugin.)

**Comment by schwamster** [comment]
thx @MichaelBellBOM . sorry for the late reply. Just to be sure, you mean the follwing line?

`
Serverless: serverless-certificate-creator version X.X.X called
`

**Comment by schwamster** [comment]
@MichaelBellBOM please check out if this version helps: 

npm i serverless-certificate-creator@1.3.1-rc-next.78

**Comment by schwamster** [comment]
released with 1.3.1

https://github.com/schwamster/serverless-certificate-creator/releases/tag/v1.3.1
