### ISSUE TITLE
Support a remove-cert command

### ISSUE THREAD

**Issue by coyoteecd** [schwamster/serverless-certificate-creator#21]
It would be nice to have a remove-cert command that uses the parameters in serverless.yml to look up and delete the certificate from ACM. This is useful in a scripted environment where you'll want to tear down the infrastructure and re-deploy from scratch.

**Comment by schwamster** [comment]
thanks for the idea and the PR -> released https://www.npmjs.com/package/serverless-certificate-creator/v/1.3.0
