### ISSUE TITLE
Should update tags on existing certificates

### ISSUE THREAD

**Issue by clar-cmp** [schwamster/serverless-certificate-creator#24]
Right now, if a certificate exists it's left alone. It would be nice to be able to update the tags for the existing certificate by changing the values in `serverless.yml`, but right now these are only added on certificate creattion.

IMHO, this should also verify that the tags match on the existing certificate and change them if they differ.

**Comment by schwamster** [comment]
Released with version v1.4.0 https://github.com/schwamster/serverless-certificate-creator/releases/tag/v1.4.0
