### ISSUE TITLE
version 1.5.0 is broken

### ISSUE THREAD

**Issue by Enase** [schwamster/serverless-certificate-creator#34]
Version is broken due to https://github.com/schwamster/serverless-certificate-creator/commit/755074e9e7b2cf4121353af3083af4d680036b42 (#31 changed code to allow enabling/disabling plugin).

The trouble is here https://github.com/schwamster/serverless-certificate-creator/blob/v1.5.0/index.js#L488
```
  getCertificateProperty(src) {
    if (!this.enabled) {
      return Promise.resolve('');
    }
```

`this.enabled` is always `undefined` due to the fact that `this.initializeVariables();` not called (called right after that).

**Comment by schwamster** [comment]
Thx for reporting. I will get on that as soon as I can

**Comment by schwamster** [comment]
thx again -> https://github.com/schwamster/serverless-certificate-creator/releases/tag/v1.5.1

**Comment by Enase** [comment]
Thanks
