### ISSUE TITLE
How to get the Cert ARN in order to reuse it later

### ISSUE THREAD

**Issue by Vad1mo** [schwamster/serverless-certificate-creator#4]
I need to get the ARN of the Generated Cert. I see it in the console but I would like to be able to feed the ARN into `AWS::CloudFront::Distribution`

Is there a way how this can be looked up?

**Comment by Vad1mo** [comment]
If it is not possible to reference the arn from the plugin in the serverless.yml, then there could be a new command added 
`write-cert-info` this command would then write a `yml`to disk  `cert-info.yml`with that content 

```yml 
acm-cert-arn: 
```

Then in the `serverless.yml` this coulld be referenced as follows 
```yml
AcmCertificateArn: ${file(../cert-info.yml):acm-cert-arn} 
```
https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-in-other-files

**Comment by schwamster** [comment]
This might not be the optimal format, but one thing that works out of the box is:

serverless info > cert-info

**Comment by Vad1mo** [comment]
Thx for the tip, this is a good workaround. 

`sls deploy --acm-cert-arn $(serverless info | grep -o -E "(arn:aws:acm:.+?\s\B)")`

**Comment by schwamster** [comment]
finally got around to implement your suggestions. you can now add a setting to the plugin configuration in serverless.yml "writeCertInfoToFile". If set to true a file called cert-info.yml will be created, default is false
